services:
  pythonapp:
    build: ./python/
    command: sh -c "while true; do python3.10 ./app/data_processing_spark.py; sleep 10s; done"
    depends_on:
      - custom_mysql
      
  custom_mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'SALES_DATABASE'
      MYSQL_ROOT_PASSWORD: 'sak479619'
    ports:
      - '3316:3306'
